# jammin_provider_music_auth Makefile

CAPABILITY_ID = "wasmcloud:example:jammin_provider_music_auth"
NAME = "jammin_provider_music_auth"
VENDOR = "Jammin Music"
PROJECT = jammin_provider_music_auth
VERSION = 0.1.0
REVISION = 0

include ./provider.mk

test::
	cargo clippy --all-targets --all-features

