// This file is @generated by wasmcloud/weld-codegen 0.6.0.
// It is not intended for manual editing.
// namespace: jammin.interfaces.oauth2

#[allow(unused_imports)]
use async_trait::async_trait;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use std::{borrow::Borrow, borrow::Cow, io::Write, string::ToString};
#[allow(unused_imports)]
use wasmbus_rpc::{
    cbor::*,
    common::{
        deserialize, message_format, serialize, Context, Message, MessageDispatch, MessageFormat,
        SendOpts, Transport,
    },
    error::{RpcError, RpcResult},
    Timestamp,
};

#[allow(dead_code)]
pub const SMITHY_VERSION: &str = "1.0";

#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct AuthorizeUserRequest {
    #[serde(default)]
    pub provider: String,
    /// OAuth2 Options: AuthorizationCode, PKCE, Refresh, ClientCredentials, DeviceCode
    #[serde(default)]
    pub grant_type: String,
    #[serde(default)]
    pub auth_code: String,
    #[serde(default)]
    pub state: String,
    #[serde(default)]
    pub csrf_state: String,
}

// Encode AuthorizeUserRequest as CBOR and append to output stream
#[doc(hidden)]
#[allow(unused_mut)]
pub fn encode_authorize_user_request<W: wasmbus_rpc::cbor::Write>(
    mut e: &mut wasmbus_rpc::cbor::Encoder<W>,
    val: &AuthorizeUserRequest,
) -> RpcResult<()>
where
    <W as wasmbus_rpc::cbor::Write>::Error: std::fmt::Display,
{
    e.array(5)?;
    e.str(&val.provider)?;
    e.str(&val.grant_type)?;
    e.str(&val.auth_code)?;
    e.str(&val.state)?;
    e.str(&val.csrf_state)?;
    Ok(())
}

// Decode AuthorizeUserRequest from cbor input stream
#[doc(hidden)]
pub fn decode_authorize_user_request(
    d: &mut wasmbus_rpc::cbor::Decoder<'_>,
) -> Result<AuthorizeUserRequest, RpcError> {
    let __result = {
        let mut provider: Option<String> = None;
        let mut grant_type: Option<String> = None;
        let mut auth_code: Option<String> = None;
        let mut state: Option<String> = None;
        let mut csrf_state: Option<String> = None;

        let is_array = match d.datatype()? {
            wasmbus_rpc::cbor::Type::Array => true,
            wasmbus_rpc::cbor::Type::Map => false,
            _ => {
                return Err(RpcError::Deser(
                    "decoding struct AuthorizeUserRequest, expected array or map".to_string(),
                ))
            }
        };
        if is_array {
            let len = d.fixed_array()?;
            for __i in 0..(len as usize) {
                match __i {
                    0 => provider = Some(d.str()?.to_string()),
                    1 => grant_type = Some(d.str()?.to_string()),
                    2 => auth_code = Some(d.str()?.to_string()),
                    3 => state = Some(d.str()?.to_string()),
                    4 => csrf_state = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        } else {
            let len = d.fixed_map()?;
            for __i in 0..(len as usize) {
                match d.str()? {
                    "provider" => provider = Some(d.str()?.to_string()),
                    "grant_type" => grant_type = Some(d.str()?.to_string()),
                    "auth_code" => auth_code = Some(d.str()?.to_string()),
                    "state" => state = Some(d.str()?.to_string()),
                    "csrf_state" => csrf_state = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        }
        AuthorizeUserRequest {
            provider: if let Some(__x) = provider {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field AuthorizeUserRequest.provider (#0)".to_string(),
                ));
            },

            grant_type: if let Some(__x) = grant_type {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field AuthorizeUserRequest.grant_type (#1)".to_string(),
                ));
            },

            auth_code: if let Some(__x) = auth_code {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field AuthorizeUserRequest.auth_code (#2)".to_string(),
                ));
            },

            state: if let Some(__x) = state {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field AuthorizeUserRequest.state (#3)".to_string(),
                ));
            },

            csrf_state: if let Some(__x) = csrf_state {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field AuthorizeUserRequest.csrf_state (#4)".to_string(),
                ));
            },
        }
    };
    Ok(__result)
}
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct AuthorizeUserResponse {
    /// indication whether the request was successful
    #[serde(default)]
    pub success: bool,
    /// If success is false, this may contain an error
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(default)]
    pub token: String,
    #[serde(default)]
    pub user_id: String,
}

// Encode AuthorizeUserResponse as CBOR and append to output stream
#[doc(hidden)]
#[allow(unused_mut)]
pub fn encode_authorize_user_response<W: wasmbus_rpc::cbor::Write>(
    mut e: &mut wasmbus_rpc::cbor::Encoder<W>,
    val: &AuthorizeUserResponse,
) -> RpcResult<()>
where
    <W as wasmbus_rpc::cbor::Write>::Error: std::fmt::Display,
{
    e.array(4)?;
    e.bool(val.success)?;
    if let Some(val) = val.error.as_ref() {
        e.str(val)?;
    } else {
        e.null()?;
    }
    e.str(&val.token)?;
    e.str(&val.user_id)?;
    Ok(())
}

// Decode AuthorizeUserResponse from cbor input stream
#[doc(hidden)]
pub fn decode_authorize_user_response(
    d: &mut wasmbus_rpc::cbor::Decoder<'_>,
) -> Result<AuthorizeUserResponse, RpcError> {
    let __result = {
        let mut success: Option<bool> = None;
        let mut error: Option<Option<String>> = Some(None);
        let mut token: Option<String> = None;
        let mut user_id: Option<String> = None;

        let is_array = match d.datatype()? {
            wasmbus_rpc::cbor::Type::Array => true,
            wasmbus_rpc::cbor::Type::Map => false,
            _ => {
                return Err(RpcError::Deser(
                    "decoding struct AuthorizeUserResponse, expected array or map".to_string(),
                ))
            }
        };
        if is_array {
            let len = d.fixed_array()?;
            for __i in 0..(len as usize) {
                match __i {
                    0 => success = Some(d.bool()?),
                    1 => {
                        error = if wasmbus_rpc::cbor::Type::Null == d.datatype()? {
                            d.skip()?;
                            Some(None)
                        } else {
                            Some(Some(d.str()?.to_string()))
                        }
                    }
                    2 => token = Some(d.str()?.to_string()),
                    3 => user_id = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        } else {
            let len = d.fixed_map()?;
            for __i in 0..(len as usize) {
                match d.str()? {
                    "success" => success = Some(d.bool()?),
                    "error" => {
                        error = if wasmbus_rpc::cbor::Type::Null == d.datatype()? {
                            d.skip()?;
                            Some(None)
                        } else {
                            Some(Some(d.str()?.to_string()))
                        }
                    }
                    "token" => token = Some(d.str()?.to_string()),
                    "user_id" => user_id = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        }
        AuthorizeUserResponse {
            success: if let Some(__x) = success {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field AuthorizeUserResponse.success (#0)".to_string(),
                ));
            },
            error: error.unwrap(),

            token: if let Some(__x) = token {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field AuthorizeUserResponse.token (#2)".to_string(),
                ));
            },

            user_id: if let Some(__x) = user_id {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field AuthorizeUserResponse.user_id (#3)".to_string(),
                ));
            },
        }
    };
    Ok(__result)
}
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct GetAuthUriRequest {
    #[serde(default)]
    pub provider: String,
    /// OAuth2 Options: AuthorizationCode, PKCE, Refresh, ClientCredentials, DeviceCode
    #[serde(default)]
    pub grant_type: String,
    #[serde(default)]
    pub client_id: String,
    #[serde(default)]
    pub client_secret: String,
    #[serde(default)]
    pub auth_url: String,
    #[serde(default)]
    pub token_url: String,
    #[serde(default)]
    pub redirect_url: String,
    #[serde(default)]
    pub scope: String,
}

// Encode GetAuthUriRequest as CBOR and append to output stream
#[doc(hidden)]
#[allow(unused_mut)]
pub fn encode_get_auth_uri_request<W: wasmbus_rpc::cbor::Write>(
    mut e: &mut wasmbus_rpc::cbor::Encoder<W>,
    val: &GetAuthUriRequest,
) -> RpcResult<()>
where
    <W as wasmbus_rpc::cbor::Write>::Error: std::fmt::Display,
{
    e.array(8)?;
    e.str(&val.provider)?;
    e.str(&val.grant_type)?;
    e.str(&val.client_id)?;
    e.str(&val.client_secret)?;
    e.str(&val.auth_url)?;
    e.str(&val.token_url)?;
    e.str(&val.redirect_url)?;
    e.str(&val.scope)?;
    Ok(())
}

// Decode GetAuthUriRequest from cbor input stream
#[doc(hidden)]
pub fn decode_get_auth_uri_request(
    d: &mut wasmbus_rpc::cbor::Decoder<'_>,
) -> Result<GetAuthUriRequest, RpcError> {
    let __result = {
        let mut provider: Option<String> = None;
        let mut grant_type: Option<String> = None;
        let mut client_id: Option<String> = None;
        let mut client_secret: Option<String> = None;
        let mut auth_url: Option<String> = None;
        let mut token_url: Option<String> = None;
        let mut redirect_url: Option<String> = None;
        let mut scope: Option<String> = None;

        let is_array = match d.datatype()? {
            wasmbus_rpc::cbor::Type::Array => true,
            wasmbus_rpc::cbor::Type::Map => false,
            _ => {
                return Err(RpcError::Deser(
                    "decoding struct GetAuthUriRequest, expected array or map".to_string(),
                ))
            }
        };
        if is_array {
            let len = d.fixed_array()?;
            for __i in 0..(len as usize) {
                match __i {
                    0 => provider = Some(d.str()?.to_string()),
                    1 => grant_type = Some(d.str()?.to_string()),
                    2 => client_id = Some(d.str()?.to_string()),
                    3 => client_secret = Some(d.str()?.to_string()),
                    4 => auth_url = Some(d.str()?.to_string()),
                    5 => token_url = Some(d.str()?.to_string()),
                    6 => redirect_url = Some(d.str()?.to_string()),
                    7 => scope = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        } else {
            let len = d.fixed_map()?;
            for __i in 0..(len as usize) {
                match d.str()? {
                    "provider" => provider = Some(d.str()?.to_string()),
                    "grant_type" => grant_type = Some(d.str()?.to_string()),
                    "client_id" => client_id = Some(d.str()?.to_string()),
                    "client_secret" => client_secret = Some(d.str()?.to_string()),
                    "auth_url" => auth_url = Some(d.str()?.to_string()),
                    "token_url" => token_url = Some(d.str()?.to_string()),
                    "redirect_url" => redirect_url = Some(d.str()?.to_string()),
                    "scope" => scope = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        }
        GetAuthUriRequest {
            provider: if let Some(__x) = provider {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field GetAuthUriRequest.provider (#0)".to_string(),
                ));
            },

            grant_type: if let Some(__x) = grant_type {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field GetAuthUriRequest.grant_type (#1)".to_string(),
                ));
            },

            client_id: if let Some(__x) = client_id {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field GetAuthUriRequest.client_id (#2)".to_string(),
                ));
            },

            client_secret: if let Some(__x) = client_secret {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field GetAuthUriRequest.client_secret (#3)".to_string(),
                ));
            },

            auth_url: if let Some(__x) = auth_url {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field GetAuthUriRequest.auth_url (#4)".to_string(),
                ));
            },

            token_url: if let Some(__x) = token_url {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field GetAuthUriRequest.token_url (#5)".to_string(),
                ));
            },

            redirect_url: if let Some(__x) = redirect_url {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field GetAuthUriRequest.redirect_url (#6)".to_string(),
                ));
            },

            scope: if let Some(__x) = scope {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field GetAuthUriRequest.scope (#7)".to_string(),
                ));
            },
        }
    };
    Ok(__result)
}
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct GetAuthUriResponse {
    #[serde(default)]
    pub success: bool,
    /// OAuth2 Options: AuthorizationCode, PKCE, Refresh, ClientCredentials, DeviceCode
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    #[serde(default)]
    pub uri: String,
    #[serde(default)]
    pub csrf_state: String,
}

// Encode GetAuthUriResponse as CBOR and append to output stream
#[doc(hidden)]
#[allow(unused_mut)]
pub fn encode_get_auth_uri_response<W: wasmbus_rpc::cbor::Write>(
    mut e: &mut wasmbus_rpc::cbor::Encoder<W>,
    val: &GetAuthUriResponse,
) -> RpcResult<()>
where
    <W as wasmbus_rpc::cbor::Write>::Error: std::fmt::Display,
{
    e.array(4)?;
    e.bool(val.success)?;
    if let Some(val) = val.error.as_ref() {
        e.str(val)?;
    } else {
        e.null()?;
    }
    e.str(&val.uri)?;
    e.str(&val.csrf_state)?;
    Ok(())
}

// Decode GetAuthUriResponse from cbor input stream
#[doc(hidden)]
pub fn decode_get_auth_uri_response(
    d: &mut wasmbus_rpc::cbor::Decoder<'_>,
) -> Result<GetAuthUriResponse, RpcError> {
    let __result = {
        let mut success: Option<bool> = None;
        let mut error: Option<Option<String>> = Some(None);
        let mut uri: Option<String> = None;
        let mut csrf_state: Option<String> = None;

        let is_array = match d.datatype()? {
            wasmbus_rpc::cbor::Type::Array => true,
            wasmbus_rpc::cbor::Type::Map => false,
            _ => {
                return Err(RpcError::Deser(
                    "decoding struct GetAuthUriResponse, expected array or map".to_string(),
                ))
            }
        };
        if is_array {
            let len = d.fixed_array()?;
            for __i in 0..(len as usize) {
                match __i {
                    0 => success = Some(d.bool()?),
                    1 => {
                        error = if wasmbus_rpc::cbor::Type::Null == d.datatype()? {
                            d.skip()?;
                            Some(None)
                        } else {
                            Some(Some(d.str()?.to_string()))
                        }
                    }
                    2 => uri = Some(d.str()?.to_string()),
                    3 => csrf_state = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        } else {
            let len = d.fixed_map()?;
            for __i in 0..(len as usize) {
                match d.str()? {
                    "success" => success = Some(d.bool()?),
                    "error" => {
                        error = if wasmbus_rpc::cbor::Type::Null == d.datatype()? {
                            d.skip()?;
                            Some(None)
                        } else {
                            Some(Some(d.str()?.to_string()))
                        }
                    }
                    "uri" => uri = Some(d.str()?.to_string()),
                    "csrf_state" => csrf_state = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        }
        GetAuthUriResponse {
            success: if let Some(__x) = success {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field GetAuthUriResponse.success (#0)".to_string(),
                ));
            },
            error: error.unwrap(),

            uri: if let Some(__x) = uri {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field GetAuthUriResponse.uri (#2)".to_string(),
                ));
            },

            csrf_state: if let Some(__x) = csrf_state {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field GetAuthUriResponse.csrf_state (#3)".to_string(),
                ));
            },
        }
    };
    Ok(__result)
}
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct UnauthorizeUserRequest {
    #[serde(default)]
    pub provider: String,
    #[serde(default)]
    pub user: String,
}

// Encode UnauthorizeUserRequest as CBOR and append to output stream
#[doc(hidden)]
#[allow(unused_mut)]
pub fn encode_unauthorize_user_request<W: wasmbus_rpc::cbor::Write>(
    mut e: &mut wasmbus_rpc::cbor::Encoder<W>,
    val: &UnauthorizeUserRequest,
) -> RpcResult<()>
where
    <W as wasmbus_rpc::cbor::Write>::Error: std::fmt::Display,
{
    e.array(2)?;
    e.str(&val.provider)?;
    e.str(&val.user)?;
    Ok(())
}

// Decode UnauthorizeUserRequest from cbor input stream
#[doc(hidden)]
pub fn decode_unauthorize_user_request(
    d: &mut wasmbus_rpc::cbor::Decoder<'_>,
) -> Result<UnauthorizeUserRequest, RpcError> {
    let __result = {
        let mut provider: Option<String> = None;
        let mut user: Option<String> = None;

        let is_array = match d.datatype()? {
            wasmbus_rpc::cbor::Type::Array => true,
            wasmbus_rpc::cbor::Type::Map => false,
            _ => {
                return Err(RpcError::Deser(
                    "decoding struct UnauthorizeUserRequest, expected array or map".to_string(),
                ))
            }
        };
        if is_array {
            let len = d.fixed_array()?;
            for __i in 0..(len as usize) {
                match __i {
                    0 => provider = Some(d.str()?.to_string()),
                    1 => user = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        } else {
            let len = d.fixed_map()?;
            for __i in 0..(len as usize) {
                match d.str()? {
                    "provider" => provider = Some(d.str()?.to_string()),
                    "user" => user = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        }
        UnauthorizeUserRequest {
            provider: if let Some(__x) = provider {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field UnauthorizeUserRequest.provider (#0)".to_string(),
                ));
            },

            user: if let Some(__x) = user {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field UnauthorizeUserRequest.user (#1)".to_string(),
                ));
            },
        }
    };
    Ok(__result)
}
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct UnauthorizeUserResponse {
    /// indication whether the request was successful
    #[serde(default)]
    pub success: bool,
    /// If success is false, this may contain an error
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

// Encode UnauthorizeUserResponse as CBOR and append to output stream
#[doc(hidden)]
#[allow(unused_mut)]
pub fn encode_unauthorize_user_response<W: wasmbus_rpc::cbor::Write>(
    mut e: &mut wasmbus_rpc::cbor::Encoder<W>,
    val: &UnauthorizeUserResponse,
) -> RpcResult<()>
where
    <W as wasmbus_rpc::cbor::Write>::Error: std::fmt::Display,
{
    e.array(2)?;
    e.bool(val.success)?;
    if let Some(val) = val.error.as_ref() {
        e.str(val)?;
    } else {
        e.null()?;
    }
    Ok(())
}

// Decode UnauthorizeUserResponse from cbor input stream
#[doc(hidden)]
pub fn decode_unauthorize_user_response(
    d: &mut wasmbus_rpc::cbor::Decoder<'_>,
) -> Result<UnauthorizeUserResponse, RpcError> {
    let __result = {
        let mut success: Option<bool> = None;
        let mut error: Option<Option<String>> = Some(None);

        let is_array = match d.datatype()? {
            wasmbus_rpc::cbor::Type::Array => true,
            wasmbus_rpc::cbor::Type::Map => false,
            _ => {
                return Err(RpcError::Deser(
                    "decoding struct UnauthorizeUserResponse, expected array or map".to_string(),
                ))
            }
        };
        if is_array {
            let len = d.fixed_array()?;
            for __i in 0..(len as usize) {
                match __i {
                    0 => success = Some(d.bool()?),
                    1 => {
                        error = if wasmbus_rpc::cbor::Type::Null == d.datatype()? {
                            d.skip()?;
                            Some(None)
                        } else {
                            Some(Some(d.str()?.to_string()))
                        }
                    }

                    _ => d.skip()?,
                }
            }
        } else {
            let len = d.fixed_map()?;
            for __i in 0..(len as usize) {
                match d.str()? {
                    "success" => success = Some(d.bool()?),
                    "error" => {
                        error = if wasmbus_rpc::cbor::Type::Null == d.datatype()? {
                            d.skip()?;
                            Some(None)
                        } else {
                            Some(Some(d.str()?.to_string()))
                        }
                    }
                    _ => d.skip()?,
                }
            }
        }
        UnauthorizeUserResponse {
            success: if let Some(__x) = success {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field UnauthorizeUserResponse.success (#0)".to_string(),
                ));
            },
            error: error.unwrap(),
        }
    };
    Ok(__result)
}
/// The Oauth2 service has 3 Operations: To Authorize the user with OAuth Provider, To Remove Authorization, and to get the initial /Authorize URI
/// wasmbus.contractId: jammin:interfaces:oauth2
/// wasmbus.providerReceive
/// wasmbus.actorReceive
#[async_trait]
pub trait Oauth2 {
    /// returns the capability contract id for this interface
    fn contract_id() -> &'static str {
        "jammin:interfaces:oauth2"
    }
    async fn authorize_user(
        &self,
        ctx: &Context,
        arg: &AuthorizeUserRequest,
    ) -> RpcResult<AuthorizeUserResponse>;
    async fn unauthorize_user(
        &self,
        ctx: &Context,
        arg: &UnauthorizeUserRequest,
    ) -> RpcResult<UnauthorizeUserResponse>;
    async fn get_auth_uri(
        &self,
        ctx: &Context,
        arg: &GetAuthUriRequest,
    ) -> RpcResult<GetAuthUriResponse>;
}

/// Oauth2Receiver receives messages defined in the Oauth2 service trait
/// The Oauth2 service has 3 Operations: To Authorize the user with OAuth Provider, To Remove Authorization, and to get the initial /Authorize URI
#[doc(hidden)]
#[async_trait]
pub trait Oauth2Receiver: MessageDispatch + Oauth2 {
    async fn dispatch(&self, ctx: &Context, message: Message<'_>) -> Result<Vec<u8>, RpcError> {
        match message.method {
            "AuthorizeUser" => {
                let value: AuthorizeUserRequest = wasmbus_rpc::common::deserialize(&message.arg)
                    .map_err(|e| RpcError::Deser(format!("'AuthorizeUserRequest': {}", e)))?;

                let resp = Oauth2::authorize_user(self, ctx, &value).await?;
                let buf = wasmbus_rpc::common::serialize(&resp)?;

                Ok(buf)
            }
            "UnauthorizeUser" => {
                let value: UnauthorizeUserRequest = wasmbus_rpc::common::deserialize(&message.arg)
                    .map_err(|e| RpcError::Deser(format!("'UnauthorizeUserRequest': {}", e)))?;

                let resp = Oauth2::unauthorize_user(self, ctx, &value).await?;
                let buf = wasmbus_rpc::common::serialize(&resp)?;

                Ok(buf)
            }
            "GetAuthUri" => {
                let value: GetAuthUriRequest = wasmbus_rpc::common::deserialize(&message.arg)
                    .map_err(|e| RpcError::Deser(format!("'GetAuthUriRequest': {}", e)))?;

                let resp = Oauth2::get_auth_uri(self, ctx, &value).await?;
                let buf = wasmbus_rpc::common::serialize(&resp)?;

                Ok(buf)
            }
            _ => Err(RpcError::MethodNotHandled(format!(
                "Oauth2::{}",
                message.method
            ))),
        }
    }
}

/// Oauth2Sender sends messages to a Oauth2 service
/// The Oauth2 service has 3 Operations: To Authorize the user with OAuth Provider, To Remove Authorization, and to get the initial /Authorize URI
/// client for sending Oauth2 messages
#[derive(Debug)]
pub struct Oauth2Sender<T: Transport> {
    transport: T,
}

impl<T: Transport> Oauth2Sender<T> {
    /// Constructs a Oauth2Sender with the specified transport
    pub fn via(transport: T) -> Self {
        Self { transport }
    }

    pub fn set_timeout(&self, interval: std::time::Duration) {
        self.transport.set_timeout(interval);
    }
}

#[cfg(not(target_arch = "wasm32"))]
impl<'send> Oauth2Sender<wasmbus_rpc::provider::ProviderTransport<'send>> {
    /// Constructs a Sender using an actor's LinkDefinition,
    /// Uses the provider's HostBridge for rpc
    pub fn for_actor(ld: &'send wasmbus_rpc::core::LinkDefinition) -> Self {
        Self {
            transport: wasmbus_rpc::provider::ProviderTransport::new(ld, None),
        }
    }
}
#[cfg(target_arch = "wasm32")]
impl Oauth2Sender<wasmbus_rpc::actor::prelude::WasmHost> {
    /// Constructs a client for actor-to-actor messaging
    /// using the recipient actor's public key
    pub fn to_actor(actor_id: &str) -> Self {
        let transport =
            wasmbus_rpc::actor::prelude::WasmHost::to_actor(actor_id.to_string()).unwrap();
        Self { transport }
    }
}

#[cfg(target_arch = "wasm32")]
impl Oauth2Sender<wasmbus_rpc::actor::prelude::WasmHost> {
    /// Constructs a client for sending to a Oauth2 provider
    /// implementing the 'jammin:interfaces:oauth2' capability contract, with the "default" link
    pub fn new() -> Self {
        let transport = wasmbus_rpc::actor::prelude::WasmHost::to_provider(
            "jammin:interfaces:oauth2",
            "default",
        )
        .unwrap();
        Self { transport }
    }

    /// Constructs a client for sending to a Oauth2 provider
    /// implementing the 'jammin:interfaces:oauth2' capability contract, with the specified link name
    pub fn new_with_link(link_name: &str) -> wasmbus_rpc::error::RpcResult<Self> {
        let transport = wasmbus_rpc::actor::prelude::WasmHost::to_provider(
            "jammin:interfaces:oauth2",
            link_name,
        )?;
        Ok(Self { transport })
    }
}
#[async_trait]
impl<T: Transport + std::marker::Sync + std::marker::Send> Oauth2 for Oauth2Sender<T> {
    #[allow(unused)]
    async fn authorize_user(
        &self,
        ctx: &Context,
        arg: &AuthorizeUserRequest,
    ) -> RpcResult<AuthorizeUserResponse> {
        let buf = wasmbus_rpc::common::serialize(arg)?;

        let resp = self
            .transport
            .send(
                ctx,
                Message {
                    method: "Oauth2.AuthorizeUser",
                    arg: Cow::Borrowed(&buf),
                },
                None,
            )
            .await?;

        let value: AuthorizeUserResponse = wasmbus_rpc::common::deserialize(&resp)
            .map_err(|e| RpcError::Deser(format!("'{}': AuthorizeUserResponse", e)))?;
        Ok(value)
    }
    #[allow(unused)]
    async fn unauthorize_user(
        &self,
        ctx: &Context,
        arg: &UnauthorizeUserRequest,
    ) -> RpcResult<UnauthorizeUserResponse> {
        let buf = wasmbus_rpc::common::serialize(arg)?;

        let resp = self
            .transport
            .send(
                ctx,
                Message {
                    method: "Oauth2.UnauthorizeUser",
                    arg: Cow::Borrowed(&buf),
                },
                None,
            )
            .await?;

        let value: UnauthorizeUserResponse = wasmbus_rpc::common::deserialize(&resp)
            .map_err(|e| RpcError::Deser(format!("'{}': UnauthorizeUserResponse", e)))?;
        Ok(value)
    }
    #[allow(unused)]
    async fn get_auth_uri(
        &self,
        ctx: &Context,
        arg: &GetAuthUriRequest,
    ) -> RpcResult<GetAuthUriResponse> {
        let buf = wasmbus_rpc::common::serialize(arg)?;

        let resp = self
            .transport
            .send(
                ctx,
                Message {
                    method: "Oauth2.GetAuthUri",
                    arg: Cow::Borrowed(&buf),
                },
                None,
            )
            .await?;

        let value: GetAuthUriResponse = wasmbus_rpc::common::deserialize(&resp)
            .map_err(|e| RpcError::Deser(format!("'{}': GetAuthUriResponse", e)))?;
        Ok(value)
    }
}
