// This file is @generated by wasmcloud/weld-codegen 0.6.0.
// It is not intended for manual editing.
// namespace: org.jammin.interfaces.oauth2

#[allow(unused_imports)]
use async_trait::async_trait;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use std::{borrow::Borrow, borrow::Cow, io::Write, string::ToString};
#[allow(unused_imports)]
use wasmbus_rpc::{
    cbor::*,
    common::{
        deserialize, message_format, serialize, Context, Message, MessageDispatch, MessageFormat,
        SendOpts, Transport,
    },
    error::{RpcError, RpcResult},
    Timestamp,
};

#[allow(dead_code)]
pub const SMITHY_VERSION: &str = "1.0";

#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct AuthorizeRequest {
    /// OAuth2 Options: AuthorizationCode, PKCE, Refresh, ClientCredentials, DeviceCode
    #[serde(rename = "grantType")]
    #[serde(default)]
    pub grant_type: String,
    #[serde(default)]
    pub provider: String,
}

// Encode AuthorizeRequest as CBOR and append to output stream
#[doc(hidden)]
#[allow(unused_mut)]
pub fn encode_authorize_request<W: wasmbus_rpc::cbor::Write>(
    mut e: &mut wasmbus_rpc::cbor::Encoder<W>,
    val: &AuthorizeRequest,
) -> RpcResult<()>
where
    <W as wasmbus_rpc::cbor::Write>::Error: std::fmt::Display,
{
    e.map(2)?;
    e.str("grantType")?;
    e.str(&val.grant_type)?;
    e.str("provider")?;
    e.str(&val.provider)?;
    Ok(())
}

// Decode AuthorizeRequest from cbor input stream
#[doc(hidden)]
pub fn decode_authorize_request(
    d: &mut wasmbus_rpc::cbor::Decoder<'_>,
) -> Result<AuthorizeRequest, RpcError> {
    let __result = {
        let mut grant_type: Option<String> = None;
        let mut provider: Option<String> = None;

        let is_array = match d.datatype()? {
            wasmbus_rpc::cbor::Type::Array => true,
            wasmbus_rpc::cbor::Type::Map => false,
            _ => {
                return Err(RpcError::Deser(
                    "decoding struct AuthorizeRequest, expected array or map".to_string(),
                ))
            }
        };
        if is_array {
            let len = d.fixed_array()?;
            for __i in 0..(len as usize) {
                match __i {
                    0 => grant_type = Some(d.str()?.to_string()),
                    1 => provider = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        } else {
            let len = d.fixed_map()?;
            for __i in 0..(len as usize) {
                match d.str()? {
                    "grantType" => grant_type = Some(d.str()?.to_string()),
                    "provider" => provider = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        }
        AuthorizeRequest {
            grant_type: if let Some(__x) = grant_type {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field AuthorizeRequest.grant_type (#0)".to_string(),
                ));
            },

            provider: if let Some(__x) = provider {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field AuthorizeRequest.provider (#1)".to_string(),
                ));
            },
        }
    };
    Ok(__result)
}
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct AuthorizeResponse {
    /// If success is false, this may contain an error
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// indication whether the request was successful
    #[serde(default)]
    pub success: bool,
}

// Encode AuthorizeResponse as CBOR and append to output stream
#[doc(hidden)]
#[allow(unused_mut)]
pub fn encode_authorize_response<W: wasmbus_rpc::cbor::Write>(
    mut e: &mut wasmbus_rpc::cbor::Encoder<W>,
    val: &AuthorizeResponse,
) -> RpcResult<()>
where
    <W as wasmbus_rpc::cbor::Write>::Error: std::fmt::Display,
{
    e.map(2)?;
    if let Some(val) = val.error.as_ref() {
        e.str("error")?;
        e.str(val)?;
    } else {
        e.null()?;
    }
    e.str("success")?;
    e.bool(val.success)?;
    Ok(())
}

// Decode AuthorizeResponse from cbor input stream
#[doc(hidden)]
pub fn decode_authorize_response(
    d: &mut wasmbus_rpc::cbor::Decoder<'_>,
) -> Result<AuthorizeResponse, RpcError> {
    let __result = {
        let mut error: Option<Option<String>> = Some(None);
        let mut success: Option<bool> = None;

        let is_array = match d.datatype()? {
            wasmbus_rpc::cbor::Type::Array => true,
            wasmbus_rpc::cbor::Type::Map => false,
            _ => {
                return Err(RpcError::Deser(
                    "decoding struct AuthorizeResponse, expected array or map".to_string(),
                ))
            }
        };
        if is_array {
            let len = d.fixed_array()?;
            for __i in 0..(len as usize) {
                match __i {
                    0 => {
                        error = if wasmbus_rpc::cbor::Type::Null == d.datatype()? {
                            d.skip()?;
                            Some(None)
                        } else {
                            Some(Some(d.str()?.to_string()))
                        }
                    }
                    1 => success = Some(d.bool()?),
                    _ => d.skip()?,
                }
            }
        } else {
            let len = d.fixed_map()?;
            for __i in 0..(len as usize) {
                match d.str()? {
                    "error" => {
                        error = if wasmbus_rpc::cbor::Type::Null == d.datatype()? {
                            d.skip()?;
                            Some(None)
                        } else {
                            Some(Some(d.str()?.to_string()))
                        }
                    }
                    "success" => success = Some(d.bool()?),
                    _ => d.skip()?,
                }
            }
        }
        AuthorizeResponse {
            error: error.unwrap(),

            success: if let Some(__x) = success {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field AuthorizeResponse.success (#1)".to_string(),
                ));
            },
        }
    };
    Ok(__result)
}
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct UnauthorizeRequest {
    #[serde(default)]
    pub provider: String,
}

// Encode UnauthorizeRequest as CBOR and append to output stream
#[doc(hidden)]
#[allow(unused_mut)]
pub fn encode_unauthorize_request<W: wasmbus_rpc::cbor::Write>(
    mut e: &mut wasmbus_rpc::cbor::Encoder<W>,
    val: &UnauthorizeRequest,
) -> RpcResult<()>
where
    <W as wasmbus_rpc::cbor::Write>::Error: std::fmt::Display,
{
    e.map(1)?;
    e.str("provider")?;
    e.str(&val.provider)?;
    Ok(())
}

// Decode UnauthorizeRequest from cbor input stream
#[doc(hidden)]
pub fn decode_unauthorize_request(
    d: &mut wasmbus_rpc::cbor::Decoder<'_>,
) -> Result<UnauthorizeRequest, RpcError> {
    let __result = {
        let mut provider: Option<String> = None;

        let is_array = match d.datatype()? {
            wasmbus_rpc::cbor::Type::Array => true,
            wasmbus_rpc::cbor::Type::Map => false,
            _ => {
                return Err(RpcError::Deser(
                    "decoding struct UnauthorizeRequest, expected array or map".to_string(),
                ))
            }
        };
        if is_array {
            let len = d.fixed_array()?;
            for __i in 0..(len as usize) {
                match __i {
                    0 => provider = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        } else {
            let len = d.fixed_map()?;
            for __i in 0..(len as usize) {
                match d.str()? {
                    "provider" => provider = Some(d.str()?.to_string()),
                    _ => d.skip()?,
                }
            }
        }
        UnauthorizeRequest {
            provider: if let Some(__x) = provider {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field UnauthorizeRequest.provider (#0)".to_string(),
                ));
            },
        }
    };
    Ok(__result)
}
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct UnauthorizeResponse {
    /// If success is false, this may contain an error
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// indication whether the request was successful
    #[serde(default)]
    pub success: bool,
}

// Encode UnauthorizeResponse as CBOR and append to output stream
#[doc(hidden)]
#[allow(unused_mut)]
pub fn encode_unauthorize_response<W: wasmbus_rpc::cbor::Write>(
    mut e: &mut wasmbus_rpc::cbor::Encoder<W>,
    val: &UnauthorizeResponse,
) -> RpcResult<()>
where
    <W as wasmbus_rpc::cbor::Write>::Error: std::fmt::Display,
{
    e.map(2)?;
    if let Some(val) = val.error.as_ref() {
        e.str("error")?;
        e.str(val)?;
    } else {
        e.null()?;
    }
    e.str("success")?;
    e.bool(val.success)?;
    Ok(())
}

// Decode UnauthorizeResponse from cbor input stream
#[doc(hidden)]
pub fn decode_unauthorize_response(
    d: &mut wasmbus_rpc::cbor::Decoder<'_>,
) -> Result<UnauthorizeResponse, RpcError> {
    let __result = {
        let mut error: Option<Option<String>> = Some(None);
        let mut success: Option<bool> = None;

        let is_array = match d.datatype()? {
            wasmbus_rpc::cbor::Type::Array => true,
            wasmbus_rpc::cbor::Type::Map => false,
            _ => {
                return Err(RpcError::Deser(
                    "decoding struct UnauthorizeResponse, expected array or map".to_string(),
                ))
            }
        };
        if is_array {
            let len = d.fixed_array()?;
            for __i in 0..(len as usize) {
                match __i {
                    0 => {
                        error = if wasmbus_rpc::cbor::Type::Null == d.datatype()? {
                            d.skip()?;
                            Some(None)
                        } else {
                            Some(Some(d.str()?.to_string()))
                        }
                    }
                    1 => success = Some(d.bool()?),
                    _ => d.skip()?,
                }
            }
        } else {
            let len = d.fixed_map()?;
            for __i in 0..(len as usize) {
                match d.str()? {
                    "error" => {
                        error = if wasmbus_rpc::cbor::Type::Null == d.datatype()? {
                            d.skip()?;
                            Some(None)
                        } else {
                            Some(Some(d.str()?.to_string()))
                        }
                    }
                    "success" => success = Some(d.bool()?),
                    _ => d.skip()?,
                }
            }
        }
        UnauthorizeResponse {
            error: error.unwrap(),

            success: if let Some(__x) = success {
                __x
            } else {
                return Err(RpcError::Deser(
                    "missing field UnauthorizeResponse.success (#1)".to_string(),
                ));
            },
        }
    };
    Ok(__result)
}
/// The Oauth2 service has a single method, calculate, which
/// calculates the factorial of its whole number parameter.
/// wasmbus.contractId: jammin:interfaces:oauth2
/// wasmbus.providerReceive
/// wasmbus.actorReceive
#[async_trait]
pub trait Oauth2 {
    /// returns the capability contract id for this interface
    fn contract_id() -> &'static str {
        "jammin:interfaces:oauth2"
    }
    async fn authorize(
        &self,
        ctx: &Context,
        arg: &AuthorizeRequest,
    ) -> RpcResult<AuthorizeResponse>;
    async fn unauthorize(
        &self,
        ctx: &Context,
        arg: &UnauthorizeRequest,
    ) -> RpcResult<UnauthorizeResponse>;
}

/// Oauth2Receiver receives messages defined in the Oauth2 service trait
/// The Oauth2 service has a single method, calculate, which
/// calculates the factorial of its whole number parameter.
#[doc(hidden)]
#[async_trait]
pub trait Oauth2Receiver: MessageDispatch + Oauth2 {
    async fn dispatch(&self, ctx: &Context, message: Message<'_>) -> Result<Vec<u8>, RpcError> {
        match message.method {
            "Authorize" => {
                let value: AuthorizeRequest = wasmbus_rpc::common::deserialize(&message.arg)
                    .map_err(|e| RpcError::Deser(format!("'AuthorizeRequest': {}", e)))?;

                let resp = Oauth2::authorize(self, ctx, &value).await?;
                let buf = wasmbus_rpc::common::serialize(&resp)?;

                Ok(buf)
            }
            "Unauthorize" => {
                let value: UnauthorizeRequest = wasmbus_rpc::common::deserialize(&message.arg)
                    .map_err(|e| RpcError::Deser(format!("'UnauthorizeRequest': {}", e)))?;

                let resp = Oauth2::unauthorize(self, ctx, &value).await?;
                let buf = wasmbus_rpc::common::serialize(&resp)?;

                Ok(buf)
            }
            _ => Err(RpcError::MethodNotHandled(format!(
                "Oauth2::{}",
                message.method
            ))),
        }
    }
}

/// Oauth2Sender sends messages to a Oauth2 service
/// The Oauth2 service has a single method, calculate, which
/// calculates the factorial of its whole number parameter.
/// client for sending Oauth2 messages
#[derive(Debug)]
pub struct Oauth2Sender<T: Transport> {
    transport: T,
}

impl<T: Transport> Oauth2Sender<T> {
    /// Constructs a Oauth2Sender with the specified transport
    pub fn via(transport: T) -> Self {
        Self { transport }
    }

    pub fn set_timeout(&self, interval: std::time::Duration) {
        self.transport.set_timeout(interval);
    }
}

#[cfg(not(target_arch = "wasm32"))]
impl<'send> Oauth2Sender<wasmbus_rpc::provider::ProviderTransport<'send>> {
    /// Constructs a Sender using an actor's LinkDefinition,
    /// Uses the provider's HostBridge for rpc
    pub fn for_actor(ld: &'send wasmbus_rpc::core::LinkDefinition) -> Self {
        Self {
            transport: wasmbus_rpc::provider::ProviderTransport::new(ld, None),
        }
    }
}
#[cfg(target_arch = "wasm32")]
impl Oauth2Sender<wasmbus_rpc::actor::prelude::WasmHost> {
    /// Constructs a client for actor-to-actor messaging
    /// using the recipient actor's public key
    pub fn to_actor(actor_id: &str) -> Self {
        let transport =
            wasmbus_rpc::actor::prelude::WasmHost::to_actor(actor_id.to_string()).unwrap();
        Self { transport }
    }
}

#[cfg(target_arch = "wasm32")]
impl Oauth2Sender<wasmbus_rpc::actor::prelude::WasmHost> {
    /// Constructs a client for sending to a Oauth2 provider
    /// implementing the 'jammin:interfaces:oauth2' capability contract, with the "default" link
    pub fn new() -> Self {
        let transport = wasmbus_rpc::actor::prelude::WasmHost::to_provider(
            "jammin:interfaces:oauth2",
            "default",
        )
        .unwrap();
        Self { transport }
    }

    /// Constructs a client for sending to a Oauth2 provider
    /// implementing the 'jammin:interfaces:oauth2' capability contract, with the specified link name
    pub fn new_with_link(link_name: &str) -> wasmbus_rpc::error::RpcResult<Self> {
        let transport = wasmbus_rpc::actor::prelude::WasmHost::to_provider(
            "jammin:interfaces:oauth2",
            link_name,
        )?;
        Ok(Self { transport })
    }
}
#[async_trait]
impl<T: Transport + std::marker::Sync + std::marker::Send> Oauth2 for Oauth2Sender<T> {
    #[allow(unused)]
    async fn authorize(
        &self,
        ctx: &Context,
        arg: &AuthorizeRequest,
    ) -> RpcResult<AuthorizeResponse> {
        let buf = wasmbus_rpc::common::serialize(arg)?;

        let resp = self
            .transport
            .send(
                ctx,
                Message {
                    method: "Oauth2.Authorize",
                    arg: Cow::Borrowed(&buf),
                },
                None,
            )
            .await?;

        let value: AuthorizeResponse = wasmbus_rpc::common::deserialize(&resp)
            .map_err(|e| RpcError::Deser(format!("'{}': AuthorizeResponse", e)))?;
        Ok(value)
    }
    #[allow(unused)]
    async fn unauthorize(
        &self,
        ctx: &Context,
        arg: &UnauthorizeRequest,
    ) -> RpcResult<UnauthorizeResponse> {
        let buf = wasmbus_rpc::common::serialize(arg)?;

        let resp = self
            .transport
            .send(
                ctx,
                Message {
                    method: "Oauth2.Unauthorize",
                    arg: Cow::Borrowed(&buf),
                },
                None,
            )
            .await?;

        let value: UnauthorizeResponse = wasmbus_rpc::common::deserialize(&resp)
            .map_err(|e| RpcError::Deser(format!("'{}': UnauthorizeResponse", e)))?;
        Ok(value)
    }
}
