// This file is @generated by wasmcloud/weld-codegen 0.6.0.
// It is not intended for manual editing.
// namespace: org.jammin.interfaces.oauth_2

#[allow(unused_imports)]
use async_trait::async_trait;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use std::{borrow::Borrow, borrow::Cow, io::Write, string::ToString};
#[allow(unused_imports)]
use wasmbus_rpc::{
    cbor::*,
    common::{
        deserialize, message_format, serialize, Context, Message, MessageDispatch, MessageFormat,
        SendOpts, Transport,
    },
    error::{RpcError, RpcResult},
    Timestamp,
};

#[allow(dead_code)]
pub const SMITHY_VERSION: &str = "1.0";

/// The Oauth2 service has a single method, calculate, which
/// calculates the factorial of its whole number parameter.
/// wasmbus.contractId: jammin:interfaces:oauth2
/// wasmbus.providerReceive
/// wasmbus.actorReceive
#[async_trait]
pub trait Oauth2 {
    /// returns the capability contract id for this interface
    fn contract_id() -> &'static str {
        "jammin:interfaces:oauth2"
    }
    /// Calculates the factorial (n!) of the input parameter
    async fn calculate(&self, ctx: &Context, arg: &u32) -> RpcResult<u64>;
}

/// Oauth2Receiver receives messages defined in the Oauth2 service trait
/// The Oauth2 service has a single method, calculate, which
/// calculates the factorial of its whole number parameter.
#[doc(hidden)]
#[async_trait]
pub trait Oauth2Receiver: MessageDispatch + Oauth2 {
    async fn dispatch(&self, ctx: &Context, message: Message<'_>) -> Result<Vec<u8>, RpcError> {
        match message.method {
            "Calculate" => {
                let value: u32 = wasmbus_rpc::common::deserialize(&message.arg)
                    .map_err(|e| RpcError::Deser(format!("'U32': {}", e)))?;

                let resp = Oauth2::calculate(self, ctx, &value).await?;
                let buf = wasmbus_rpc::common::serialize(&resp)?;

                Ok(buf)
            }
            _ => Err(RpcError::MethodNotHandled(format!(
                "Oauth2::{}",
                message.method
            ))),
        }
    }
}

/// Oauth2Sender sends messages to a Oauth2 service
/// The Oauth2 service has a single method, calculate, which
/// calculates the factorial of its whole number parameter.
/// client for sending Oauth2 messages
#[derive(Debug)]
pub struct Oauth2Sender<T: Transport> {
    transport: T,
}

impl<T: Transport> Oauth2Sender<T> {
    /// Constructs a Oauth2Sender with the specified transport
    pub fn via(transport: T) -> Self {
        Self { transport }
    }

    pub fn set_timeout(&self, interval: std::time::Duration) {
        self.transport.set_timeout(interval);
    }
}

#[cfg(not(target_arch = "wasm32"))]
impl<'send> Oauth2Sender<wasmbus_rpc::provider::ProviderTransport<'send>> {
    /// Constructs a Sender using an actor's LinkDefinition,
    /// Uses the provider's HostBridge for rpc
    pub fn for_actor(ld: &'send wasmbus_rpc::core::LinkDefinition) -> Self {
        Self {
            transport: wasmbus_rpc::provider::ProviderTransport::new(ld, None),
        }
    }
}
#[cfg(target_arch = "wasm32")]
impl Oauth2Sender<wasmbus_rpc::actor::prelude::WasmHost> {
    /// Constructs a client for actor-to-actor messaging
    /// using the recipient actor's public key
    pub fn to_actor(actor_id: &str) -> Self {
        let transport =
            wasmbus_rpc::actor::prelude::WasmHost::to_actor(actor_id.to_string()).unwrap();
        Self { transport }
    }
}

#[cfg(target_arch = "wasm32")]
impl Oauth2Sender<wasmbus_rpc::actor::prelude::WasmHost> {
    /// Constructs a client for sending to a Oauth2 provider
    /// implementing the 'jammin:interfaces:oauth2' capability contract, with the "default" link
    pub fn new() -> Self {
        let transport = wasmbus_rpc::actor::prelude::WasmHost::to_provider(
            "jammin:interfaces:oauth2",
            "default",
        )
        .unwrap();
        Self { transport }
    }

    /// Constructs a client for sending to a Oauth2 provider
    /// implementing the 'jammin:interfaces:oauth2' capability contract, with the specified link name
    pub fn new_with_link(link_name: &str) -> wasmbus_rpc::error::RpcResult<Self> {
        let transport = wasmbus_rpc::actor::prelude::WasmHost::to_provider(
            "jammin:interfaces:oauth2",
            link_name,
        )?;
        Ok(Self { transport })
    }
}
#[async_trait]
impl<T: Transport + std::marker::Sync + std::marker::Send> Oauth2 for Oauth2Sender<T> {
    #[allow(unused)]
    /// Calculates the factorial (n!) of the input parameter
    async fn calculate(&self, ctx: &Context, arg: &u32) -> RpcResult<u64> {
        let buf = wasmbus_rpc::common::serialize(arg)?;

        let resp = self
            .transport
            .send(
                ctx,
                Message {
                    method: "Oauth2.Calculate",
                    arg: Cow::Borrowed(&buf),
                },
                None,
            )
            .await?;

        let value: u64 = wasmbus_rpc::common::deserialize(&resp)
            .map_err(|e| RpcError::Deser(format!("'{}': U64", e)))?;
        Ok(value)
    }
}
