# oauth2 Makefile

CAPABILITY_ID = "wasmcloud:example:oauth_2"
NAME = "oauth2"
VENDOR = "jammin"
PROJECT = oauth_2
VERSION = 0.1.0
REVISION = 0

include ./provider.mk

test::
	cargo clippy --all-targets --all-features

