# oauth2-provider Makefile

CAPABILITY_ID = "jammin:interfaces:oauth2"
NAME = "oauth2-provider"
VENDOR = "jammin"
PROJECT = oauth2-provider
VERSION = 0.1.0
REVISION = 0

include ./provider.mk

test::
	cargo clippy --all-targets --all-features

